apiVersion: apps/v1
kind: Deployment
metadata:
 name: service-a
 labels:
   app: service-a
spec:
 replicas: 1
 selector:
   matchLabels:
     app: service-a
 template:
   metadata:
     labels:
       app: service-a
   spec:
     containers:
     - name: service-a
       image: khasham1/service-a-java:latest
       imagePullPolicy: Always
       ports:
       - containerPort: 8080
       env:
       - name: SERVICE_B_URL
         value: "http://service-b-svc:8080/data"
       - name: SPRING_APPLICATION_NAME
         value: "Service A"
       resources: {}
       readinessProbe:
         httpGet:
           path: /actuator/health
           port: 8080
         initialDelaySeconds: 15
         periodSeconds: 5
       livenessProbe:
         httpGet:
           path: /actuator/health
           port: 8080
         initialDelaySeconds: 30
         periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
 name: service-a-svc
spec:
 type: ClusterIP
 selector:
   app: service-a
 ports:
 - protocol: TCP
   port: 80
   targetPort: 8080
